<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Concerns\HasUuids;

class DataLengkapMahasiswaProdi extends Model
{
    use HasUuids;

    public $incrementing = false;
    protected $keyType = 'string';

    public $table = 'data_lengkap_mahasiswa_prodi';

    public $fillable = [
        'tanggal_lahir',
        'nama_program_studi',
        'nama_status_mahasiswa',
        'id_status_mahasiswa',
        'nim',
        'id_periode_masuk',
        'nama_periode_masuk',
        'id_registrasi_mahasiswa',
        'jalur_masuk',
        'nama_jalur_masuk',
        'id_mahasiswa',
        'nama_mahasiswa',
        'jenis_kelamin',
        'tempat_lahir',
        'id_agama',
        'nama_agama',
        'nik',
        'nisn',
        'npwp',
        'id_negara',
        'kewarganegaraan',
        'jalan',
        'dusun',
        'rt',
        'rw',
        'kelurahan',
        'kode_pos',
        'id_wilayah',
        'nama_wilayah',
        'id_jenis_tinggal',
        'nama_jenis_tinggal',
        'id_alat_transportasi',
        'nama_alat_transportasi',
        'telepon',
        'handphone',
        'email',
        'penerima_kps',
        'nomor_kps',
        'nama_ayah',
        'tanggal_lahir_ayah',
        'id_pendidikan_ayah',
        'nama_pendidikan_ayah',
        'id_pekerjaan_ayah',
        'nama_pekerjaan_ayah',
        'id_penghasilan_ayah',
        'nama_penghasilan_ayah',
        'nik_ibu',
        'nama_ibu_kandung',
        'tanggal_lahir_ibu',
        'id_pendidikan_ibu',
        'nama_pendidikan_ibu',
        'id_pekerjaan_ibu',
        'nama_pekerjaan_ibu',
        'id_penghasilan_ibu',
        'nama_penghasilan_ibu',
        'nama_wali',
        'tanggal_lahir_wali',
        'id_pendidikan_wali',
        'nama_pendidikan_wali',
        'id_pekerjaan_wali',
        'nama_pekerjaan_wali',
        'id_penghasilan_wali',
        'nama_penghasilan_wali',
        'id_kebutuhan_khusus_mahasiswa',
        'nama_kebutuhan_khusus_mahasiswa',
        'id_kebutuhan_khusus_ayah',
        'nama_kebutuhan_khusus_ayah',
        'id_kebutuhan_khusus_ibu',
        'nama_kebutuhan_khusus_ibu',
        'sks_diakui',
        'id_perguruan_tinggi_asal',
        'nama_perguruan_tinggi_asal',
        'id_prodi_asal',
        'nama_program_studi_asal',
        'status_sync',
        'id_prodi'
    ];

    protected $casts = [
        'id' => 'string',
        'tanggal_lahir' => 'date',
        'nama_program_studi' => 'string',
        'nama_status_mahasiswa' => 'string',
        'nim' => 'string',
        'nama_periode_masuk' => 'string',
        'id_registrasi_mahasiswa' => 'string',
        'jalur_masuk' => 'string',
        'nama_jalur_masuk' => 'string',
        'id_mahasiswa' => 'string',
        'nama_mahasiswa' => 'string',
        'jenis_kelamin' => 'string',
        'tempat_lahir' => 'string',
        'nama_agama' => 'string',
        'id_negara' => 'string',
        'kewarganegaraan' => 'string',
        'jalan' => 'string',
        'dusun' => 'string',
        'rt' => 'string',
        'rw' => 'string',
        'kelurahan' => 'string',
        'id_wilayah' => 'string',
        'nama_wilayah' => 'string',
        'nama_jenis_tinggal' => 'string',
        'nama_alat_transportasi' => 'string',
        'email' => 'string',
        'nama_ayah' => 'string',
        'tanggal_lahir_ayah' => 'date',
        'nama_pendidikan_ayah' => 'string',
        'nama_pekerjaan_ayah' => 'string',
        'nama_penghasilan_ayah' => 'string',
        'nik_ibu' => 'string',
        'nama_ibu_kandung' => 'string',
        'tanggal_lahir_ibu' => 'date',
        'nama_pendidikan_ibu' => 'string',
        'nama_pekerjaan_ibu' => 'string',
        'nama_penghasilan_ibu' => 'string',
        'nama_wali' => 'string',
        'tanggal_lahir_wali' => 'date',
        'nama_pendidikan_wali' => 'string',
        'nama_pekerjaan_wali' => 'string',
        'nama_penghasilan_wali' => 'string',
        'nama_kebutuhan_khusus_mahasiswa' => 'string',
        'nama_kebutuhan_khusus_ayah' => 'string',
        'nama_kebutuhan_khusus_ibu' => 'string',
        'id_perguruan_tinggi_asal' => 'string',
        'nama_perguruan_tinggi_asal' => 'string',
        'id_prodi_asal' => 'string',
        'nama_program_studi_asal' => 'string',
        'status_sync' => 'string',
        'id_prodi' => 'string'
    ];

    public static array $rules = [
        'tanggal_lahir' => 'required',
        'nama_program_studi' => 'required|string|max:255',
        'nama_status_mahasiswa' => 'required|string|max:255',
        'id_status_mahasiswa' => 'required',
        'nim' => 'required|string|max:255',
        'id_periode_masuk' => 'required',
        'nama_periode_masuk' => 'required|string|max:255',
        'id_registrasi_mahasiswa' => 'required|string|max:36',
        'jalur_masuk' => 'nullable|string|max:255',
        'nama_jalur_masuk' => 'nullable|string|max:255',
        'id_mahasiswa' => 'required|string|max:36',
        'nama_mahasiswa' => 'required|string|max:255',
        'jenis_kelamin' => 'required|string|max:255',
        'tempat_lahir' => 'required|string|max:255',
        'id_agama' => 'required',
        'nama_agama' => 'required|string|max:255',
        'nik' => 'required',
        'nisn' => 'nullable',
        'npwp' => 'nullable',
        'id_negara' => 'required|string|max:255',
        'kewarganegaraan' => 'nullable|string|max:255',
        'jalan' => 'nullable|string|max:255',
        'dusun' => 'nullable|string|max:255',
        'rt' => 'nullable|string|max:255',
        'rw' => 'nullable|string|max:255',
        'kelurahan' => 'nullable|string|max:255',
        'kode_pos' => 'nullable',
        'id_wilayah' => 'required|string|max:255',
        'nama_wilayah' => 'nullable|string|max:255',
        'id_jenis_tinggal' => 'nullable',
        'nama_jenis_tinggal' => 'nullable|string|max:255',
        'id_alat_transportasi' => 'nullable',
        'nama_alat_transportasi' => 'nullable|string|max:255',
        'telepon' => 'nullable',
        'handphone' => 'nullable',
        'email' => 'nullable|string|max:255',
        'penerima_kps' => 'required',
        'nomor_kps' => 'nullable',
        'nama_ayah' => 'nullable|string|max:255',
        'tanggal_lahir_ayah' => 'nullable',
        'id_pendidikan_ayah' => 'nullable',
        'nama_pendidikan_ayah' => 'nullable|string|max:255',
        'id_pekerjaan_ayah' => 'nullable',
        'nama_pekerjaan_ayah' => 'nullable|string|max:255',
        'id_penghasilan_ayah' => 'nullable',
        'nama_penghasilan_ayah' => 'nullable|string|max:255',
        'nik_ibu' => 'nullable|string|max:255',
        'nama_ibu_kandung' => 'nullable|string|max:255',
        'tanggal_lahir_ibu' => 'nullable',
        'id_pendidikan_ibu' => 'nullable',
        'nama_pendidikan_ibu' => 'nullable|string|max:255',
        'id_pekerjaan_ibu' => 'nullable',
        'nama_pekerjaan_ibu' => 'nullable|string|max:255',
        'id_penghasilan_ibu' => 'nullable',
        'nama_penghasilan_ibu' => 'nullable|string|max:255',
        'nama_wali' => 'nullable|string|max:255',
        'tanggal_lahir_wali' => 'nullable',
        'id_pendidikan_wali' => 'nullable',
        'nama_pendidikan_wali' => 'nullable|string|max:255',
        'id_pekerjaan_wali' => 'nullable',
        'nama_pekerjaan_wali' => 'nullable|string|max:255',
        'id_penghasilan_wali' => 'nullable',
        'nama_penghasilan_wali' => 'nullable|string|max:255',
        'id_kebutuhan_khusus_mahasiswa' => 'nullable',
        'nama_kebutuhan_khusus_mahasiswa' => 'nullable|string|max:255',
        'id_kebutuhan_khusus_ayah' => 'nullable',
        'nama_kebutuhan_khusus_ayah' => 'nullable|string|max:255',
        'id_kebutuhan_khusus_ibu' => 'nullable',
        'nama_kebutuhan_khusus_ibu' => 'nullable|string|max:255',
        'sks_diakui' => 'nullable',
        'id_perguruan_tinggi_asal' => 'nullable|string|max:36',
        'nama_perguruan_tinggi_asal' => 'nullable|string|max:255',
        'id_prodi_asal' => 'nullable|string|max:36',
        'nama_program_studi_asal' => 'nullable|string|max:255',
        'status_sync' => 'required|string|max:255',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'id_prodi' => 'required|string|max:36'
    ];

    
}
